### ISSUE TITLE
LanguageProvider.test failure due to child setter call

### ISSUE THREAD

**Issue by BrianJVarley** [zeljkoX/react-native-localization-example#1]
Hi @zeljkoX I've pulled in your example which is a good improvement over using a singleton instance of strings. But I notice the LanguageProvider tests fails due to the LanguageStore.setLanguage being called in the chain.

```
FAIL  src\modules\languageProvider\__tests__\LanguageProvider-test.js
  ● renders correctly

    TypeError: _this.strings.setLanguage is not a function

      at LanguageStore.setLanguage (src\modules\languageProvider\LanguageStore.js:25:15)
      at new LanguageProvider (src\modules\languageProvider\LanguageProvider.js:30:16)

```

I posted a question about this here if you have ideas? 

https://stackoverflow.com/questions/55222209/how-to-hoist-a-jest-dependency-mock-over-actual-dependency

**Comment by BrianJVarley** [comment]
Resolved with this solution - https://stackoverflow.com/a/55233086/1829251
